#import decimal

#SIZE_CHANGE_IN_PRICE_CHARGED = decimal.Decimal(.10)

SIZE_CHANGE_IN_PRICE_CHARGED = .10

SIZE_CHANGE_IN_NUMBER_OF_ATTENDEES_OBSERVED = 15

PRICE_SENSITIVITY = SIZE_CHANGE_IN_NUMBER_OF_ATTENDEES_OBSERVED / SIZE_CHANGE_IN_PRICE_CHARGED

#PRICE_SENSITIVITY_DECIMAL = SIZE_CHANGE_IN_NUMBER_OF_ATTENDEES_OBSERVED / SIZE_CHANGE_IN_PRICE_CHARGED

#PRICE_SENSITIVITY = round(PRICE_SENSITIVITY_DECIMAL)
